import './globals.css'
import Navbar from './navbar'
import { PT_Serif} from 'next/font/google'
const font = PT_Serif({ subsets: ['latin'], weight: ["400", "700"] })

export const metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">

      <body className={` ${font.className} relative`} >
        <Navbar />

        {children}</body>
    </html>
  )
}
